
spring.application.name=ms-geolocalizacion
server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/Geolocalizacion?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false